### ISSUE TITLE
Potential risk of credentials leak

### ISSUE THREAD

**Issue by urmilshroff** [zacharee/LockscreenWidgets#1]
Hey @zacharee, you've publicly committed your `[google-services.json](https://www.github.com/zacharee/LockscreenWidgets/tree/master/app%2Fgoogle-services.json)` file. I suggest you take care of it immediately before some kind of security breach happens, if it hasn't already.

**Comment by zacharee** [comment]
Is it a security issue? All the information in that file is compiled directly into the APK inside the `strings.xml` file.

**Comment by urmilshroff** [comment]
> Is it a security issue? All the information in that file is compiled directly into the APK inside the `strings.xml` file.

Yes, it is. I'm guessing it's a connection to your Firebase? Someone could use that same file in another malicious modification of your app and compromise the database.

**Comment by zacharee** [comment]
There is no database. It's just Crashlytics. Even if it were a database, someone could just take the strings.xml from the APK.

**Comment by urmilshroff** [comment]
Are you sure? I think it encrypts it or does something to hide it. Either way, it's best practice not to commit such keys/files to your public repo.
