### ISSUE TITLE
Tasker (Autoinput) and possibly other accessibility service apps stop working

### ISSUE THREAD

**Issue by rom4ster** [zacharee/LockscreenWidgets#16]
I have a tasker script set up like so, enabling lockscreen widget makes the profile never fire. The script is trying to detect the lock screen security text via autoinput... The run log never prints anything so it is not detecting anything. Is there a way to let other accessibility apps actually use the screen and not hog it? 
![image](https://user-images.githubusercontent.com/19560977/204328266-d0b702cf-13cf-4f14-9abc-bdee51a0468d.png)

**Comment by zacharee** [comment]
Can you share your Tasker profile?

**Comment by rom4ster** [comment]
> Can you share your Tasker profile?

    Profile: Bye Pass
    	Event: AutoInput UI Update [ Configuration:Apps: System UI
    Text: PIN required for routine security check ]
    
    
    
    Enter Task: Test
    
    A1: Wait [
         MS: 0
         Seconds: 1
         Minutes: 0
         Hours: 0
         Days: 0 ]
    
    A2: Variable Clear [
         Name: %Test ]
    
    A3: Authentication Dialog [
         Type: Biometric
         Title: sup
         Number Of Attempts: 3
         Read Result To: %Test
         Timeout (Seconds): 10 ]
    
    A4: [X] Flash [
         Text: Hi
         Continue Task Immediately: On
         Dismiss On Click: On ]
    
    A5: [X] Popup [
         Text: %Test
         Layout: Popup
         Timeout (Seconds): 1
         Show Over Keyguard: On ]
    
    A6: Variable Clear [
         Name: %Test ]
    
    A7: [X] AutoInput UI Query [
         Configuration: Text: PIN
         Regex: true
         Only Visible: true
         Timeout (Seconds): 20
         Structure Output (JSON, etc): On ]
    
    A8: [X] Popup [
         Title: G
         Text: %aiapp
         Layout: Popup
         Timeout (Seconds): 17
         Show Over Keyguard: On ]
    
    A9: Variable Set [
         Name: %pass
         To: 1234
         Structure Output (JSON, etc): On ]
    
    A10: Read File [
          File: Documents/x
          To Var: %pass
          Structure Output (JSON, etc): On ]
    
    A11: Variable Split [
          Name: %pass
          Splitter: , ]
    
    A12: Variable Set [
          Name: %maxcnt
          To: 7
          Structure Output (JSON, etc): On ]
    
    A13: Variable Set [
          Name: %loc
          To: 280 1360,540 1360,800 1360,280 1620,540 1620,800 1620,280 1880,540 1880,800 1880,280 2140,540 2140,800 2140
          Structure Output (JSON, etc): On ]
    
    A14: Variable Split [
          Name: %loc
          Splitter: ,
          Delete Base: On ]
    
    A15: Variable Set [
          Name: %cnt
          To: 0
          Structure Output (JSON, etc): On ]
    
    <LOOP>
    A16: Variable Set [
          Name: %cnt
          To: 1+%cnt
          Do Maths: On
          Max Rounding Digits: 3
          Structure Output (JSON, etc): On ]
    
    A17: Variable Set [
          Name: %lol
          To: %pass(%cnt)
          Structure Output (JSON, etc): On ]
    
    A18: Run Shell [
          Command: input tap %loc(%lol)
          Timeout (Seconds): 0
          Use Root: On
          Use Global Namespace: On ]
    
    A19: Wait [
          MS: 15
          Seconds: 0
          Minutes: 0
          Hours: 0
          Days: 0 ]
    
    A20: [X] Flash [
          Text: input tap %loc(%lol)
          Continue Task Immediately: On
          Dismiss On Click: On ]
    
    A21: Goto [
          Type: Action Label
          Label: LOOP ]
        If  [ %cnt < %maxcnt ]

**Comment by zacharee** [comment]
What device is this? I tested on a Samsung Galaxy S22 Ultra on Android 13 and the AutoInput UI Update event successfully fires when Lockscreen Widgets is enabled and the "Draw unlock pattern" text is shown above the pattern input.

**Comment by rom4ster** [comment]
Sony Xperia 1 III Android 12
