### ISSUE TITLE
Multiple Widgets

### ISSUE THREAD

**Issue by Serralq** [zacharee/LockscreenWidgets#17]
Being able to add multiple widgets to my home screen at the same time without needing to swipe to see them all. This way I can overlay my widgets over my lock screen and effectively have a fully custom lock screen. 

One possible solution is use a widget that contains other widgets. This would allow for "one widget" so I wouldn't have to scroll through to see all the widgets within the parent widgets but I haven't been able to find anything like this so that's why I'm adding this feature request.

**Comment by BroJac5246** [comment]
![Screenshot_20230122-093906-909.png](https://user-images.githubusercontent.com/104146239/213921623-e0e7df42-7730-4856-91b1-a4d11eebd4a1.png)

Like this?

**Comment by Serralq** [comment]
Yea, something like that, but most apps have it so that you have to activate it in some way such as running a shortcut for the widgets to appear and so it wouldn't work with my use case for lockscreen widget, but please send the name of your screenshot over to see if I could use it.

**Comment by BroJac5246** [comment]
> Yea, something like that, but most apps have it so that you have to activate it in some way such as running a shortcut for the widgets to appear and so it wouldn't work with my use case for lockscreen widget, but please send the name of your screenshot over to see if I could use it.

I did this using Lockscreen Widgets. You need to go to settings and increase the values of "Columns per Page" and "Rows per Page".

**Comment by Serralq** [comment]
Thanks it works perfectly
