### ISSUE TITLE
HIde when showing notifications option will never make the widget(s) appear

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/LockscreenWidgets#2]
Installed version is 1.1.2
The hide when showing notifications option, even with notification listener active, shows no widget when there are no notifications.
If notification listener looks for every type of notifications, consider switching to watching just non-swipeable notifications. Switching to non-swipeable and non-silent notifications (Android 8+) would be even better.

My phone is Oneplus 6T running EvolutionX (Custom ROM) based on Android 10.0

**Comment by zacharee** [comment]
It currently checks for notifications above minimum priority. Are there no notifications posted at all?

**Comment by shmykelsa** [comment]
I have 2 ongoing notifications, with minimum priority, and still widgets are not shown

**Comment by zacharee** [comment]
This should be fixed in 1.2.0
