### ISSUE TITLE
Widget doesn't hide when Notification Shade partially expanded (i.e. 4 QS tiles shown)

### ISSUE THREAD

**Issue by e-t-l** [zacharee/LockscreenWidgets#21]
In the partially-expanded state of the Notification Shade (for Android 12 and 13 / any OS with the wide "pill"-style QS tiles, this would be when only the top four QS tiles are shown, with no brightness slider), the lockscreen widget does not disappear, even when the appropriate setting is activated. When the Notifcation Shade is _fully_ expanded, that's when the widget disappears. 

Is this partially-expanded state something the Accessibility Service can detect? 

(Let me know if my description is unclear and you need me to screen record a video of it)

**Comment by zacharee** [comment]
This should be fixed in the next version.
