### ISSUE TITLE
Resize widgets in rows 

### ISSUE THREAD

**Issue by Lorestan00** [zacharee/LockscreenWidgets#22]
While it's great if you select rows you can have more than one widget on a page. Could you add a way to resize each widget. At the moment you can end up with lots of space see attached ![Screenshot_20230824-111513.png](https://github.com/zacharee/LockscreenWidgets/assets/81394097/b47870df-e59a-42d7-bffd-e439d16ac645)

**Comment by zacharee** [comment]
You can increase the row count for the frame and have one widget take up more rows proportional to the space you want it to have.
