### ISSUE TITLE
Pixel 8 pro

### ISSUE THREAD

**Issue by Eric112490** [zacharee/LockscreenWidgets#23]
Pixel 8 pro not showing widgets, and can you add ability to disable on landscape mode. It interferes with button navigation when it thinks it's in landscape mode.

It's showing the widgets in the drawer and on lock screen... Kind of clunky arranging them though.

**Comment by BroJac5246** [comment]
> It shows on drawer 
>
> It shows on lock screen
>
> But it doesn't show in app
>
> Oh I just noticed that it's probably not the design to have the widgets listed on the app side.
> 
> Also rearranging the apps in drawer is a nightmare, is there a way to like free form place?

I'm not the developer of the app, so I don't really know. But I have noticed that it's hard to arrange apps in the app drawer. Your best bet would be resizing the widgets to not fit together, but yes, I agree that it should be better.
