### ISSUE TITLE
Cannot add Home Assistant widgets

### ISSUE THREAD

**Issue by MacHoel** [zacharee/LockscreenWidgets#24]
Hi,

Tried out from GPlay with a Samsung A7 Lite tablet (Android 13).
Maybe the required configuration of the widget is the issue..?
Hopefully I did not miss any trivial config, and the attached log will be of help.

[lockscreen_widgets_debug_2023-11-12_11_38_44.txt](https://github.com/zacharee/LockscreenWidgets/files/13327776/lockscreen_widgets_debug_2023-11-12_11_38_44.txt)

**Comment by zacharee** [comment]
This should be fixed.
