### ISSUE TITLE
Delay in widget animation

### ISSUE THREAD

**Issue by SterlJ** [zacharee/LockscreenWidgets#28]
When adding a widget on the lock screen there is a half second delay for it to disappear once the phone is unlocked. Just tad a annoying and takes away the seamlessness.

**Comment by BroJac5246** [comment]
I'm not familiar with how this works but this is likely to be something that is a device/Android limitation. I've noticed there's a delay between when the notification shade is pulled down and when it's reported (see the debug settings), and I would assume that is what's causing this.

**Comment by zacharee** [comment]
Unfortunately there isn't much I can do about this. It's up to Android to decide when Lockscreen Widgets receives screen update events, and those events will always only be sent after the change is complete, so there's inherent delay.
