### ISSUE TITLE
Link to Play store in the readme

### ISSUE THREAD

**Issue by C0rn3j** [zacharee/LockscreenWidgets#29]
I understand not wanting to link places which have compiled and made the code available elsewhere, but please link the paid Play Store version of yours, I only found out it exists by accident.

Would be nice to also mention if this works nicely with AOD and not just the screen-on lockscreen.

**Comment by zacharee** [comment]
I added a link in the Readme to the Play Store.

Lockscreen Widgets isn't made to work on the AOD. If it works with your manufacturer's version, that's an added bonus, but it's actually meant to hide itself before the AOD activates.

**Comment by C0rn3j** [comment]
> Lockscreen Widgets isn't made to work on the AOD

I would have appreciated if that was also mentioned in the readme + Play page.  
The black backgrounds on the Play page implied otherwise to me.
