### ISSUE TITLE
App should let the user add widgets from the main activity

### ISSUE THREAD

**Issue by shmykelsa** [zacharee/LockscreenWidgets#3]
The current steps to add some widgets is:

1) Get to lockscreen
2) Go to add page and press the add button
3) Actually unlock the phone
4) Add the widget

To check the widget I should go back to loscreen. The whole thing is not very comfortable.

If the main activity had a little space on the bottom to scroll through the actual widgets (with the actual size) and add some, on every widget add steps 1 and 3 would be skipped, making the whole process of adding multiple widgets much more comfortable.

Also widgets' order should be user-arrangeable.

**Comment by zacharee** [comment]
You can arrange the widgets. Hold down on one and drag.

I'll look into ways to add widgets without using the lock screen.

**Comment by zacharee** [comment]
There's now a button in the toolbar to add a widget from the app itself in 1.2.0.
